name: RetailMind AI CI/CD

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest

    env:
    AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
    AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
    AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"


      - name: Install Dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Tests
        run: |
          pytest